sudo: required
services:
  - dockerfile

before_install:
  - docker build -t ranjit-ash/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ranjit-ash/multi-docker npm test

after_success: 
  - docker build -t ranjit-ash/multi-client ./client
  - docker build -t ranjit-ash/multi-nginx ./nginx
  - docker build -t ranjit-ash/multi-server ./server
  - docker build -t ranjit-ash/multi-worker ./wroker
# Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push ranjit-ash/multi-client
  - docker push ranjit-ash/multi-nginx
  - docker push ranjit-ash/multi-server
  - docker push ranjit-ash/multi-worker
